### ISSUE TITLE
Not compiling...

### ISSUE THREAD

**Issue by MrGlasspoole** [filfat-Studios-AB/cordova-plugin-fullscreen#1]
If i try to run the App in Android Studio with this plugin i get:
```
O:\Workspace\Cordova\GertyTouch\platforms\android\src\com\filfatstudios\Fullscreen\Fullscreen.java
Error:(29, 170) error: ')' expected
Error:(29, 175) error: illegal start of expression
Error:(29, 208) error: ';' expected
Error:(29, 280) error: not a statement
Error:(29, 318) error: ';' expected
```
In Fullscreen.java i see:
Cannot resolve symbol 'Context'
and
Cannot resolve symbol 'Activity'

**Comment by filfat** [comment]
Oups, forgot to deploy the fix; will do shortly.

**Comment by filfat** [comment]
Updated.
You'll need to update your local copy to version 1.0.0 :)
